// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWZphfLplD0VMvtu0jxQVDMY6UXvI4mw',
    appId: '1:302087771391:web:5336b2d6f686e11c8068ca',
    messagingSenderId: '302087771391',
    projectId: 'lil-circle-fcdc2',
    authDomain: 'lil-circle-fcdc2.firebaseapp.com',
    storageBucket: 'lil-circle-fcdc2.firebasestorage.app',
    measurementId: 'G-MSSTE1B4HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGHNMJfMECf9X9MvzZSlpLkydJaAk--_A',
    appId: '1:302087771391:android:954d77de0a2f9ce78068ca',
    messagingSenderId: '302087771391',
    projectId: 'lil-circle-fcdc2',
    storageBucket: 'lil-circle-fcdc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsG5ga9W1whYR2NJT3G9JsupsUojI4cnA',
    appId: '1:302087771391:ios:d0a49ebaa5319de08068ca',
    messagingSenderId: '302087771391',
    projectId: 'lil-circle-fcdc2',
    storageBucket: 'lil-circle-fcdc2.firebasestorage.app',
    iosBundleId: 'com.example.lilCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsG5ga9W1whYR2NJT3G9JsupsUojI4cnA',
    appId: '1:302087771391:ios:d0a49ebaa5319de08068ca',
    messagingSenderId: '302087771391',
    projectId: 'lil-circle-fcdc2',
    storageBucket: 'lil-circle-fcdc2.firebasestorage.app',
    iosBundleId: 'com.example.lilCircle',
  );

}